version: "3.9"

services:
    app:
        container_name: app
        build:
          context: ./php
          network: host
        ports:
            - "9000:9000"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./../:/var/www
        working_dir: /var/www
        networks:
            - backend
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./../:/var/www
        networks:
            - backend
        ports:
            - "80:80"
    db:
        container_name: db
        image: postgres:16.3
        ports:
            - "5432:5432"
        networks:
            - backend
        volumes:
            - ./postgres/data:/var/lib/postgres
        environment:
            POSTGRES_PASSWORD: bichig
            POSTGRES_USER: root
            POSTGRES_DB: bichig
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    backend:
        name: backend
