version: "3.9"

services:
    app:
        container_name: app
        build:
          context: ./php
          network: host
        ports:
            - "9000:9000"
        volumes:
            - ./../:/var/www
        working_dir: /var/www
        networks:
            - backend
            - nginx_proxy_manager_default
        environment:
            PHP_FPM_POOL_NAME: "bichig_chat_php"
            AUTORUN_ENABLED: true
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./../:/var/www
        networks:
            - backend
            - nginx_proxy_manager_default
    db:
        container_name: db
        image: postgres:16.3
        ports:
            - "5432:5432"
        networks:
            - backend
        volumes:
            - ./postgres/data:/var/lib/postgres
        environment:
            POSTGRES_PASSWORD: bichig
            POSTGRES_USER: root
            POSTGRES_DB: bichig
    redis:
        container_name: redis
        image: redis:6
        command: "redis-server --appendonly yes --requirepass redispassword"
        ports:
            - "6379:6379"
        networks:
            - backend
    queue_worker:
        container_name: queue_worker
        image: serversideup/php:8.3-fpm
        volumes:
            - ./../:/var/www
        command: ["php", "/var/www/artisan", "queue:work", "--tries=3"]
        environment:
            PHP_FPM_POOL_NAME: "bichig_chat_horizon"
        depends_on:
            - redis
        networks:
            - backend
#    minio:
#        container_name: minio
#        image: quay.io/minio/minio
#        command: server /data --console-address ":9001"
#        ports:
#            - "9000:9000"
#            - "9001:9001"
#        volumes:
#            - ./minio/data:/data
#        environment:
#            MINIO_ROOT_USER: "minioadmin"
#            MINIO_ROOT_PASSWORD: "minioadmin"
#            MINIO_DEFAULT_BUCKETS: "bichig"
#        networks:
#            - backend
    reverb:
        container_name: reverb
        image: serversideup/php:8.3-fpm
        volumes:
            - ./../:/var/www
        command: ["php", "/var/www/artisan", "reverb:start"]
        environment:
            PHP_FPM_POOL_NAME: "bichig_chat_reverb"
        ports:
            - "8080:8080"
        networks:
            - backend

networks:
    backend:
        name: backend
    nginx_proxy_manager_default:
        name: nginx_proxy_manager_default
        external: true
